name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "alexgalkin94" --password-stdin
        docker build . --file Dockerfile --tag tournament:latest
        docker push alexgalkin94/tournament:latest
